name: "flickr_personalized"
backend: "onnxruntime"
max_batch_size: 128
input [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [768]
  },
  {
    name: "user_idx"
    data_type: TYPE_INT64
    dims: [1]
    reshape { shape: [] }
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [1]
  }
]
instance_group [
  {
    count: 2
    kind: KIND_GPU
    gpus: [0]
  }
]
dynamic_batching {
  preferred_batch_size: [4, 8, 16, 32, 64, 128]
  max_queue_delay_microseconds: 50
}
